---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: etcd-encryption
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.DS Data Security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: etcd-encryption
      spec:
        remediationAction: enforce
        severity: med
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - default
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: config.openshift.io/v1
            kind: APIServer
            metadata:
              name: cluster
            spec:
              encryption:
                type: aescbc
