---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: ldap-authentication
  namespace: acm-policies
placementRef:
  name: ldap-authentication
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: ldap-authentication
  kind: Policy
  apiGroup: policy.open-cluster-management.io
