---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: LDAP
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        email: ["mail"]
        id: ["dn"]
        name: ["cn"]
        preferredUsername: ["uid"]
      bindDN: "uid=admin,cn=users,cn=accounts,dc=zmlabs,dc=site"
      bindPassword:
        name: ldap-bind-password
      insecure: false
      ca:
        name: idm-tls-ca
      url: "ldaps://idm.zmlabs.site:636/cn=users,cn=accounts,dc=zmlabs,dc=site?uid"
