---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace: acm-configuration
  name: acm-configuration
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: acm-configuration
