---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-configuration
  namespace: acm-configuration
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: rhacm-root
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: acm-configuration
spec:
  channel: acm-configuration/acm-configuration
  placement:
    placementRef:
      kind: PlacementRule
      name: acm-configuration
