---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: authorization-development
  namespace: acm-subscriptions
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      purpose: development
