---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ldap-bind-password-group-sync
  namespace: acm-secrets
spec:
  clusterConditions:
  - status: 'True'
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: purpose
      operator: In
      values:
      - development
      - production
