---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: openshift-cluster-admins
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: ocp-admin 
