---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ldap-group-sync-production
  namespace: acm-subscriptions
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: ldap-group-sync-production
